#version 450

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform texture2D InputTexture;
layout(set = 0, binding = 1) uniform sampler InputSampler;
layout(set = 0, binding = 2, std430) buffer OutputBuffer
{
    vec4 Value;
};

void main()
{
    Value = textureLod(
        sampler2D(InputTexture, InputSampler),
        vec2(0.5, 0.5),
        2.0);
}
